= else

<pre>else(default: <a href="https://docs.kaskada.com/docs/data-model#type-constraints">any</a>, value: <a href="https://docs.kaskada.com/docs/data-model#type-constraints">any</a>) -> any</pre>

Return the `value` if it is non-`null`, `default` otherwise.

### Parameters
* default: The result to use if `value` is `null`.
* value: The result to prefer if it is non-`null`.

Note the order of arguments has `default` first, so that you can use
it with the pipe syntax to provide default values, as in
`value | else(default)`.

### Results

For each row, returns `value` if it is non-`null` in that row, or
`default` if `value is `null`.

**Tags:** [logical](#logical-functions)

.Example: Choosing between two values

====In this example the result is `Input.a` if it is non-`null`, and `Input.b`
otherwise. This may be combined with [`if`](#if) to conditionaly `null` out
cases to implement various logical operations.

When chaining multiple conditionals, it may be better to use [`coalesce`](#coalesce).

= Query
```
Input.a | else(Input.b)
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,key,a,b
2021-01-01T00:00:00.000000000Z,X,57.8,63
2021-01-02T00:00:00.000000000Z,Y,,86.3
2021-01-03T00:00:00.000000000Z,X,6873,
2021-01-04T00:00:00.000000000Z,X,,

|===


= Output CSV
[header,format=csv]
|===
time,key,a,b,result
2021-01-01T00:00:00.000000000,X,57.8,63.0,57.8
2021-01-02T00:00:00.000000000,Y,,86.3,86.3
2021-01-03T00:00:00.000000000,X,6873.0,,6873.0
2021-01-04T00:00:00.000000000,X,,,

|===

====


.Example: Providing a default value

====This example shows how to use `else` to provide a default value for a
possibly `null` value.

= Query
```
Input.a | else(42.0)
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,key,a,b
2021-01-01T00:00:00.000000000Z,X,57.8,63
2021-01-02T00:00:00.000000000Z,Y,,86.3
2021-01-03T00:00:00.000000000Z,X,6873,
2021-01-04T00:00:00.000000000Z,X,,

|===


= Output CSV
[header,format=csv]
|===
time,key,a,b,result
2021-01-01T00:00:00.000000000,X,57.8,63.0,57.8
2021-01-02T00:00:00.000000000,Y,,86.3,42.0
2021-01-03T00:00:00.000000000,X,6873.0,,6873.0
2021-01-04T00:00:00.000000000,X,,,42.0

|===

====

