= lag

<pre>lag(const n: <a href="https://docs.kaskada.com/docs/data-model#scalars">i64</a>, input: <a href="https://docs.kaskada.com/docs/data-model#type-constraints">ordered</a>) -> ordered</pre>

Returns a lagging value of `e`.

### Parameters
* n: The amount of lag to retrieve.
  For instance, `n = 1` is the previous non-`null` value, `n = 2` is the non-`null` value before that, etc.
* input: The value to retrieve.

### Results
Returns a new column with the same type as `input`, but with each row containing the value of `input` from `n` rows earlier (counting only non-`null` rows for the current entity).

**Tags:** [time](#time-functions)

.Example: Lag for Previous Value

===== Query
```
lag(1, Input.n)
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,key,n
1996-03-21T00:00:00-00:00,Ben,1
1996-04-21T00:00:00-00:00,Ryan,2
1996-05-21T00:00:00-00:00,Ryan,3
1996-06-21T00:00:00-00:00,Ryan,4
1996-07-21T00:00:00-00:00,Ben,5
1996-08-21T00:00:00-00:00,Ben,6

|===


= Output CSV
[header,format=csv]
|===
time,key,n,result
1996-03-21T00:00:00.000000000,Ben,1,
1996-04-21T00:00:00.000000000,Ryan,2,
1996-05-21T00:00:00.000000000,Ryan,3,2
1996-06-21T00:00:00.000000000,Ryan,4,3
1996-07-21T00:00:00.000000000,Ben,5,1
1996-08-21T00:00:00.000000000,Ben,6,5

|===

====


.Example: Lag for Average Change

====This example uses `lag` to compute the average difference between values of `n`.

= Query
```
# Will always be non-`null` after the first non-`null` `Input.n`.
let prev_value = Input.n | lag(1)

# Will be `null` if current `Input.n` is `null`.
let difference = Input.n - prev_value
in
{
  difference,
  mean_difference: mean(difference),
} | extend({ time: time_of($input), key: first(Input.key) })
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,key,n
1996-03-21T00:00:00-00:00,Ben,1
1996-04-21T00:00:00-00:00,Ryan,2
1996-05-21T00:00:00-00:00,Ryan,
1996-06-21T00:00:00-00:00,Ryan,4
1996-07-21T00:00:00-00:00,Ben,5
1996-08-21T00:00:00-00:00,Ben,6

|===


= Output CSV
[header,format=csv]
|===
time,key,difference,mean_difference
1996-03-21T00:00:00.000000000,Ben,,
1996-04-21T00:00:00.000000000,Ryan,,
1996-05-21T00:00:00.000000000,Ryan,,
1996-06-21T00:00:00.000000000,Ryan,2,2.0
1996-07-21T00:00:00.000000000,Ben,4,4.0
1996-08-21T00:00:00.000000000,Ben,1,2.5

|===

====

