= logical_or

<pre>logical_or(a: <a href="https://docs.kaskada.com/docs/data-model#scalars">bool</a>, b: <a href="https://docs.kaskada.com/docs/data-model#scalars">bool</a>) -> bool</pre>

Returns the logical disjunction (OR) of two booleans.

This is the function used for the binary operation `a or b`.

### Parameters
* a: The left-hand side of the disjunction.
* b: The right-hand side of the disjunction.

### Results
* Returns `true` if `a` or `b` are `true`.
* Returns `false` if `a` and `b` are both `false`.
* Returns `null` if `a` or `b` are `null`.

**Tags:** [logical](#logical-functions) [operator](#operators)

.Example: Logical Or

===== Query
```
Input.a or Input.b
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,subsort,key,a,b
2021-01-01T00:00:00.000000000Z,0,A,true,false
2021-01-02T00:00:00.000000000Z,0,B,true,true
2021-01-03T00:00:00.000000000Z,0,A,false,true
2021-01-04T00:00:00.000000000Z,0,A,false,false
2021-01-05T00:00:00.000000000Z,0,A,,true
2021-02-01T00:00:00.000000000Z,0,B,true,
2021-02-02T00:00:00.000000000Z,0,A,,false
2021-03-01T00:00:00.000000000Z,0,B,false,

|===


= Output CSV
[header,format=csv]
|===
time,subsort,key,a,b,result
2021-01-01T00:00:00.000000000,0,A,true,false,true
2021-01-02T00:00:00.000000000,0,B,true,true,true
2021-01-03T00:00:00.000000000,0,A,false,true,true
2021-01-04T00:00:00.000000000,0,A,false,false,false
2021-01-05T00:00:00.000000000,0,A,,true,true
2021-02-01T00:00:00.000000000,0,B,true,,true
2021-02-02T00:00:00.000000000,0,A,,false,
2021-03-01T00:00:00.000000000,0,B,false,,

|===

====

