= sliding

<pre>sliding(const duration: <a href="https://docs.kaskada.com/docs/data-model#scalars">i64</a>, condition: <a href="https://docs.kaskada.com/docs/data-model#scalars">bool</a>) -> window</pre>

Configures sliding windowed aggregations.

Configures aggregations to slide over a window of inputs, where the width
of the window is determined by the number of times (`duration`) the
`condition` is `true`.

Given the function `sliding(3, hourly())`, at 8:27 PM the window starts
at 6:00 PM, with points at 7:00 and 8:00 PM. Once time advances to 9:00 PM,
the `condition` is `true` and the window slides forward to start at 7:00 PM.
The 3 most recent points where `condition` was `true` are 7:00 PM, 8:00 PM,
and 9:00 PM.

### Parameters
* duration: The number of sliding intervals to use in the window.
* condition: The condition used to determine when the window should slide.

### Results
Returns a window behavior that can be used with an [aggregation](#aggregation-functions)
to configure windowed aggregations.

**Tags:** [window](#window-functions)

.Example: Sliding Over 2 Days

====Produces the sum of `Input.n` over a window of 2 days.

NOTE: The time and key are not available on the rows created by the ticks.
The expression here uses `extend`, `time_of` and `first` to compute the `time` and `key` columns for all rows.

= Query
```
{ n: Input.n, result: sum(Input.n, window = sliding(2, daily())) }
# Compute time and key for all rows, even the ticks.
| extend({ time: time_of($input), key: first(Input.key) })
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,key,n
1996-12-19T00:00:00-00:00,Ben,1
1996-12-19T00:00:00-00:00,Ryan,2
1996-12-20T00:00:00-00:00,Ben,3
1996-12-20T01:00:00-00:00,Ben,4
1996-12-21T00:00:00-00:00,Ryan,5
1996-12-21T00:00:00-00:00,Ben,6
|===


= Output CSV
[header,format=csv]
|===
time,key,n,result
1996-12-19T00:00:00.000000000,Ben,1,1
1996-12-19T00:00:00.000000000,Ryan,2,2
1996-12-19T00:00:00.000000000,Ryan,,2
1996-12-19T00:00:00.000000000,Ben,,1
1996-12-20T00:00:00.000000000,Ben,3,4
1996-12-20T00:00:00.000000000,Ryan,,2
1996-12-20T00:00:00.000000000,Ben,,4
1996-12-20T01:00:00.000000000,Ben,4,7
1996-12-21T00:00:00.000000000,Ryan,5,5
1996-12-21T00:00:00.000000000,Ben,6,13
1996-12-21T00:00:00.000000000,Ryan,,5
1996-12-21T00:00:00.000000000,Ben,,13

|===

====


.Example: Sliding Over 3 Events

====In this example, the `condition` evaluates to `true` when the input
is valid, meaning the width of the window is 3 `Input` rows.

= Query
```
mean(Input.n, window = sliding(3, is_valid(Input)))
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,subsort,key,n
1996-12-19T00:00:00-00:00,0,Ben,1
1996-12-19T00:00:00-00:00,0,Ryan,2
1996-12-20T00:00:00-00:00,0,Ben,3
1996-12-20T01:00:00-00:00,0,Ben,4
1996-12-21T00:00:00-00:00,0,Ryan,5
1996-12-21T00:00:00-00:00,0,Ben,6
|===


= Output CSV
[header,format=csv]
|===
time,subsort,key,n,result
1996-12-19T00:00:00.000000000,0,Ben,1,1.0
1996-12-19T00:00:00.000000000,0,Ryan,2,2.0
1996-12-20T00:00:00.000000000,0,Ben,3,2.0
1996-12-20T01:00:00.000000000,0,Ben,4,2.6666666666666665
1996-12-21T00:00:00.000000000,0,Ryan,5,3.5
1996-12-21T00:00:00.000000000,0,Ben,6,4.333333333333333

|===

====

