= sub

<pre>sub(a: <a href="https://docs.kaskada.com/docs/data-model#type-constraints">number</a>, b: <a href="https://docs.kaskada.com/docs/data-model#type-constraints">number</a>) -> number</pre>

Returns the difference of two numbers.

This is the function used for the binary operation `a - b`.

### Parameters
* a: The left-hand side of the subtraction.
* b: The right-hand side of the subtraction.

Note: Both `a` and `b` are promoted to a compatible numeric type
following the [numeric type coercion rules](docs:data-model#numeric-type-coercion-table).

### Results
Returns a numeric column of the promoted numeric type compatible with both `a` and `b`.
The result contains `null` if `a` or `b` was null at that row.
Otherwise the row contains the difference of `a` and `b`.

**Tags:** [math](#math-functions) [operator](#operators)

.Example: Subtraction

===== Query
```
Input.a - Input.b
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,key,a,b
2021-01-01T00:00:00.000000000Z,A,5.7,1.2
2021-01-02T00:00:00.000000000Z,A,6.3,0.4
2021-01-03T00:00:00.000000000Z,B,,3.7
2021-01-03T00:00:00.000000000Z,A,13.2,
2021-01-04T00:00:00.000000000Z,A,12.2,0

|===


= Output CSV
[header,format=csv]
|===
time,key,a,b,result
2021-01-01T00:00:00.000000000,A,5.7,1.2,4.5
2021-01-02T00:00:00.000000000,A,6.3,0.4,5.8999999999999995
2021-01-03T00:00:00.000000000,B,,3.7,
2021-01-03T00:00:00.000000000,A,13.2,,
2021-01-04T00:00:00.000000000,A,12.2,0.0,12.2

|===

====

