= zip_min

<pre>zip_min(a: <a href="https://docs.kaskada.com/docs/data-model#type-constraints">ordered</a>, b: <a href="https://docs.kaskada.com/docs/data-model#type-constraints">ordered</a>) -> ordered</pre>

Returns the minimum of two values.

This returns the minimum of two values. See the aggregation [`min`](#min) for
the minimum of values in a column up to and including the current row.

### Parameters
* a, b: The two values to take the minimum of.

Note: Both `a` and `b` are promoted to a compatible ordered type
following the [numeric type coercion rules](docs:data-model#numeric-type-coercion-table).

### Results
Returns a numeric column of the promoted type.
Each row contains the value from `a` if `a` is less than `b`, otherwise it contains `b`.
Specifically, if `a` or `b` is `NaN` then `b` will be returned. If `a`
or `b` are `null`, then `b` will be returned.

**Tags:** [math](#math-functions)

.Example: Zip Min

===== Query
```
zip_min(Input.a, Input.b)
```

= Table: Input

* **Name**: `Input`
* **Time Column**: `time`
* **Group Column**: `key`
* **Grouping**: `grouping`

[%header,format=csv]
|===
time,key,a,b
2021-01-01T00:00:00.000000000Z,A,5.7,1.2
2021-01-01T00:00:00.000000000Z,A,6.3,0.4
2021-01-02T00:00:00.000000000Z,B,,3.7
2021-01-03T00:00:00.000000000Z,A,13.2,

|===


= Output CSV
[header,format=csv]
|===
time,key,a,b,result
2021-01-01T00:00:00.000000000,A,5.7,1.2,1.2
2021-01-01T00:00:00.000000000,A,6.3,0.4,0.4
2021-01-02T00:00:00.000000000,B,,3.7,
2021-01-03T00:00:00.000000000,A,13.2,,

|===

====

